version: 1.0.{build}-{branch}
image: Visual Studio 2017

init:
  - git config --global core.eol lf
  - git config --global core.autocrlf false
  - ps: mkdir C:\downloads | Out-Null

environment:
  DOCKER_VERSION: 1.10.0
  DOCKER_MACHINE_VERSION: 0.4.1
build_script:
  - choco install -yr cygwin > nul
  - choco install -yr jq
  - choco install -yr docker -version %DOCKER_VERSION%
  - choco install -yr docker-machine -version %DOCKER_MACHINE_VERSION%


test: off

on_failure:
  - docker version
  - docker-compose version