version: 1.0.{build}-{branch}
image: Visual Studio 2017

init:
  - git config --global core.eol lf
  - git config --global core.autocrlf false
  - ps: mkdir C:\downloads | Out-Null

build_script:
  - ps: .\appveyor-build.ps1
test: off

on_failure:
  - docker version
  - docker-compose version