version: 1.0.{build}
image: Visual Studio 2017

init:
  - git config --global core.eol lf
  - git config --global core.autocrlf false
  - ps: mkdir C:\downloads | Out-Null

install:
#  - ps: |
#      cd C:\downloads
#      Start-FileDownload "http://download.virtualbox.org/virtualbox/5.1.6/VirtualBox-5.1.6-110634-Win.exe"
#      Start-FileDownload "http://download.virtualbox.org/virtualbox/5.1.6/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack"
#      Start-Process -FilePath "VirtualBox-5.1.6-110634-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox" -Wait
#      cd $env:APPVEYOR_BUILD_FOLDER
#  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
#  - VBoxManage extpack install C:\downloads\Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack
#  - VBoxManage -v
#  - ssh -V
#  - ipconfig /all

build_script:
  - $version = "17.05.0-ce"
  - $wc = New-Object net.webclient
  - $wc.DownloadFile("https://get.docker.com/builds/Windows/x86_64/docker-$version.zip", "$env:TEMP\docker.zip")
  - Expand-Archive -Path "$env:TEMP\docker.zip" -DestinationPath $env:ProgramFiles -Force
  - Remove-Item "$env:TEMP\docker.zip"
  - Start-Service docker

  - docker-compose start
  - yarn
  - yarn bootstrap

test: off

test_script:
  - yarn test-unit
  - docker-compose stop

on_failure:
  - yarn --version
  - docker version
  - docker-compose version