image: Visual Studio 2017

build_script:
  - choco install docker-machine
  - VBoxManage extpack install C:\downloads\Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack
  - VBoxManage -v
  - docker-machine create --driver virtualbox default
  - docker-machine env default
  - choco install docker-compose
  - docker-compose build
  - docker-compose create
  - docker-compose start
  - yarn
  - yarn bootstrap

test: off

test_script:
  - yarn test-unit
  - docker-compose stop

on_failure:
  - yarn --version
  - docker version
  - docker-compose version