image: Visual Studio 2017

init:
  - git config --global core.eol lf
  - git config --global core.autocrlf false
  - ps: mkdir C:\downloads | Out-Null

install:
#  - ps: |
#      cd C:\downloads
#      Start-FileDownload "http://download.virtualbox.org/virtualbox/5.1.6/VirtualBox-5.1.6-110634-Win.exe"
#      Start-FileDownload "http://download.virtualbox.org/virtualbox/5.1.6/Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack"
#      Start-Process -FilePath "VirtualBox-5.1.6-110634-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox" -Wait
#      cd $env:APPVEYOR_BUILD_FOLDER
#  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
#  - VBoxManage extpack install C:\downloads\Oracle_VM_VirtualBox_Extension_Pack-5.1.6-110634.vbox-extpack
#  - VBoxManage -v
#  - ssh -V
#  - ipconfig /all

build_script:
  - choco install docker
  - choco install docker-machine
  - choco install docker-compose
#  - docker-machine create --driver virtualbox default
#  - docker-machine env default
  - choco install docker-compose
  - docker-compose build
#  - docker-compose create
  - docker-compose start
  - yarn
  - yarn bootstrap

test: off

test_script:
  - yarn test-unit
  - docker-compose stop

on_failure:
  - yarn --version
  - docker version
  - docker-compose version