version: '2'
services:
  #unohouse.com.pl
  unohouse-app:
    build: ./vhosts/unohouse-com-pl
    container_name: app
    links:
      - unohousedb:unohousedb
    volumes:
      - ./www:/var/www
    environment:
      - VIRTUAL_HOST=unohouse.dev
  # ===

  #docs.unohouse.com.pl
  docs-unohouse-com-pl:
    image: swaggerapi/swagger-ui
    container_name: docs
    ports:
      - "82:8080"
    environment:
      - VIRTUAL_HOST=docs.unohouse.dev
  # ===

  #yui Jenkins
  yui-unohouse-com-pl:
    build: ./vhosts/yui
    container_name: yui
    ports:
        - "50000:50000"
        - "8080:8080"
    volumes:
        - /var/jenkins_home
        - ./www:/var/www
        - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
  # ===

  #yui.unohouse.com.pl
  yui-proxy-pass:
    build: ./vhosts/yui-proxy
    container_name: yui-proxy
    environment:
        - VIRTUAL_HOST=yui.unohouse.dev
  # ===

  # MySQL
  unohousedb:
    build: ./docker/unohousedb
    container_name: unohousedb
    ports:
      - "3306:3306"
      - "13306:3306"
    volumes:
      - /var/mysql:/var/lib/mysql
    volumes_from:
      - storage
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: unohouse

  #PMA
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - unohousedb
    environment:
      - PMA_HOSTS=unohousedb
      - VIRTUAL_HOST=pma.unohouse.dev
      - VIRTUAL_PORT=3306
      - PMA_ARBITRARY=0
      - PMA_USER=root
      - PMA_PASSWORD=unohouse
      - PMA_ABSOLUTE_URI=pma.unohouse.dev
    volumes:
      - /sessions
      - /var/run/docker.sock:/tmp/docker.sock:ro

  unomemcache:
    build: ./docker/unohousememcached
    container_name: memcache
    ports:
      - "11211:11211"

  # Proxy
  nginx-proxy:
      build: ./docker/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./logs/nginx/:/var/log/nginx

  elk:
    image: willdurand/elk
    container_name: elk
    ports:
        - 81:80
    volumes:
        - ./elk/logstash:/etc/logstash
        - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - unohouse-app
        - nginx-proxy

  #######################################
  # FTP (vsftpd)
  #######################################
  ftp:
    build:
      context: docker/vsftpd/
    container_name: ftp
    volumes_from:
      - storage
    volumes:
      - ./:/application/

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    container_name: storage
    volumes:
      - /storage