#195.181.209.40
vhost-unohouse-salwa-com-pl:
  build: ./vhosts/unohouse-salwa-com-pl
  container_name: unohouse
  links:
      - unohousedb:unohousedb
  volumes:
      - /var/www:/var/www
  environment:
    - VIRTUAL_HOST=195.181.209.40

#unohouse.com.pl
vhost-unohouse-salwa-com-pl:
  build: ./vhosts/unohouse-com-pl
  container_name: unohouse.com.pl
  links:
      - unohousedb:unohousedb
  volumes:
      - /var/www:/var/www
  environment:
    - VIRTUAL_HOST=unohouse.com.pl
# ===

#docs.unohouse.com.pl
vhost-docs-unohouse-salwa-com-pl:
  build: ./vhosts/docs-unohouse-com-pl
  container_name: unohouse-docs
  volumes:
      - /var/www:/var/www
  environment:
    - VIRTUAL_HOST=docs.unohouse.com.pl
#===

# MySQL
unohousedb:
  build: ./internal/unohousedb
  container_name: unohousedb
  ports:
    - "3306:3306"
  volumes:
    - /var/mysql:/var/lib/mysql
  environment:
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: unohouse

unomemcache:
  build: ./internal/unohousememcached
  container_name: unomemcache
  ports:
    - "127.0.0.1:11211:11211"

# Proxy
nginx-proxy:
    build: ./internal/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


