version: '2'
services:
  #unohouse.com.pl
  vhost-unohouse-salwa-com-pl:
    build: ./vhosts/unohouse-com-pl
    container_name: app
    links:
      - unohousedb:unohousedb
    volumes:
      - /var/www:/var/www
    environment:
      - VIRTUAL_HOST=unohouse.com.pl
  # ===

  #docs.unohouse.com.pl
  vhost-docs-unohouse-salwa-com-pl:
    container_name: docs
    build: ./vhosts/docs-unohouse-com-pl
    volumes:
      - /var/www:/var/www
    environment:
      - VIRTUAL_HOST=docs.unohouse.com.pl
  # ===

  #jenkins Jenkins
  yui-unohouse-salwa-com-pl:
    build: ./vhosts/jenkins
    container_name: jenkins
    ports:
        - "50000:50000"
        - "8080:8080"
    volumes:
        - /var/jenkins_home
        - /var/www:/var/www
        - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
  # ===

  #jenkins.unohouse.com.pl
  yui-proxy-pass:
    build: ./vhosts/yui-proxy
    container_name: jenkins-proxy
    volumes:
        - /var/www:/var/www
        - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
        - VIRTUAL_HOST=jenkins.unohouse.com.pl
  # ===

  # MySQL
  unohousedb:
    build: ./docker/unohousedb
    container_name: unohousedb
    ports:
      - "3306:3306"
    volumes:
      - /var/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: unohouse

  unomemcache:
    build: ./docker/unohousememcached
    container_name: memcache
    ports:
      - "127.0.0.1:11211:11211"

  # Proxy
  nginx-proxy:
      build: ./docker/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./certs:/etc/nginx/certs
