version: "2"
services:
  #unohouse.com.pl
  unohouse-app:
    build: ./vhosts/unohouse-com-pl
    container_name: uno_app
    ports:
      - "8000:80"
    links:
      - unohouse-db:unohouse-db
    volumes:
      - ./www:/var/www
    environment:
      - VIRTUAL_HOST=unohouse.local

  # MySQL
  unohouse-db:
    build: ./docker/unohousedb
    container_name: uno_db
    ports:
      - "3306:3306"
      - "13306:3306"
    volumes:
      - /var/mysql:/var/lib/mysql
    volumes_from:
      - storage
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: unohouse

  unohouse-memcache:
    build: ./docker/unohousememcached
    container_name: uno_memcache
    ports:
      - "11211:11211"

  unohouse-nodejs:
    build: docker/nodejs/.
    container_name: uno_nodejs
    restart: always
    ports:
      - "1520:1520"
      - "4200:4200"
    volumes:
      - ./www:/var/www
    tty: true

  storage:
    build:
      context: docker/storage/
    container_name: uno_storage
    volumes:
      - /storage
