version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
      
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker containers
          command: |
            set -x
            docker-compose build
      - run:
          name: Run Docker containers
          command: |
            set -x
            docker-compose up -d
      - run:
          name: List Docker containers
          command: |
            set -x
            docker ps